# Generated by Django 3.0.3 on 2020-02-21 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('doctor', models.CharField(max_length=10)),
                ('log', models.TextField()),
                ('important_points', models.CharField(max_length=1000)),
                ('medications', models.TextField()),
                ('operation_time', models.DateTimeField()),
                ('report', models.FileField(upload_to='')),
            ],
        ),
    ]
